app:
    build: ./
    dockerfile: DockerFile-App
    dns:
        - 8.8.8.8
        - 114.114.114
    links:
        - mariadb
        - redis
mariadb:
    image: mariadb
    command: mysqld
    environment:
        - 'MYSQL_ROOT_PASSWORD=root123456'
        - 'MYSQL_DATABASE=ctrs'
        - 'MYSQL_USER=ctrs'
        - 'MYSQL_PASSWORD=ctrs123456'
    dns:
        - 8.8.8.8
        - 114.114.114
    expose:
        - '3306'
redis:
    image: redis
    dns:
        - 8.8.8.8
        - 114.114.114
    expose:
        - '6379'
